// Copyright Epic Games, Inc. All Rights Reserved.

#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

/** Singles */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CanProcessInput)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CanProcessDirectionalInput)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_CanMove)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_IsInParryWindow)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_IsRecoveringAfterParry)

/** Attributes */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Attack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Defense)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Lives)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_MaxWalkSpeed)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Attribute_Poise)

/** Directions */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Direction_None)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Direction_Down)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Direction_Left)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Direction_Right)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Direction_Up)

/** Gameplay States */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayState_Default)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayState_Attack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayState_Defense)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayState_Rune)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_GameplayState_Combat)

/** Status */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Sprint)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Airborne)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Staggered)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Status_Invulnerable)

/** Actions */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_None)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Attack)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Defense)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Rune)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Dodge)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Sprint)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_RecoverFromParry)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Deathblow)

/** -- Runes */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Fireball)

/** -- AI */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_FireCleave)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Combo2)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_Kick)

/** -- States */
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_AttackState)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_CombatState)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_DefenseState)
UE_DECLARE_GAMEPLAY_TAG_EXTERN(TAG_Action_RuneState)



